# Generated by Django 3.2.13 on 2022-05-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default='pictures', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
